# Generated by Django 5.2.7 on 2025-10-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0002_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_score', models.FloatField(default=100)),
                ('final_exam_full_score', models.FloatField(default=50)),
                ('midterm_full_score', models.FloatField(default=20)),
                ('section_exam_full_score', models.FloatField(default=15)),
                ('year_work_full_score', models.FloatField(default=15)),
                ('is_summer', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_grade_sheet', to='courses.course')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_score', models.FloatField(default=0)),
                ('section_exam_score', models.FloatField(default=0)),
                ('final_exam_score', models.FloatField(default=0)),
                ('year_work_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('letter_grade', models.CharField(blank=True, max_length=3)),
                ('is_passed', models.BooleanField(default=False)),
                ('course_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='structure.courseregistration')),
                ('grade_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grades.gradesheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('student_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.studentstructure')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'student_structure'], name='grades_stud_student_e9b2be_idx')],
                'unique_together': {('grade_sheet', 'student')},
            },
        ),
    ]
