# Generated by Django 5.2.7 on 2025-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('role', models.CharField(choices=[('subject_doctor', 'دكتور مادة'), ('admin_doctor', 'دكتور إداري'), ('teaching_assistant', 'معيد')], default='subject_doctor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('national_id', models.CharField(max_length=14)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('sec_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
