# Generated by Django 5.2.7 on 2025-10-30 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='current_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='student',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='student_history', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['national_id'], name='accounts_do_nationa_23a446_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['national_id'], name='accounts_st_nationa_bcf65f_idx'),
        ),
    ]
