# Generated by Django 5.2.7 on 2025-12-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),   # سيبها زي ما هي
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='structures',
            field=models.ManyToManyField(
                blank=True,
                related_name='student_history',
                to='structure.StudentStructure',
            ),
        ),
    ]