# Generated by Django 5.2.7 on 2025-12-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251209_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='structures',
        ),
        migrations.AddField(
            model_name='student',
            name='structures_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
