# Generated by Django 5.2.7 on 2025-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_structures_student_structures_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='structures_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
