# Generated by Django 5.2.7 on 2025-12-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('structure', '0008_alter_repeatcourseregistration_retake_attempt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('carry_courses', models.ManyToManyField(blank=True, related_name='dropped_out_students', to='structure.carrycourse')),
                ('repeat_courses', models.ManyToManyField(blank=True, related_name='dropped_out_students', to='structure.repeatcourseregistration')),
                ('structures', models.ManyToManyField(blank=True, related_name='dropped_out_students', to='structure.studentstructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_out_record', to='accounts.student')),
                ('summer_courses', models.ManyToManyField(blank=True, related_name='dropped_out_students', to='structure.summercourseregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated_at', models.DateTimeField(auto_now_add=True)),
                ('structures', models.ManyToManyField(blank=True, related_name='graduated_students', to='structure.studentstructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_record', to='accounts.student')),
            ],
        ),
    ]
