# Generated by Django 5.2.7 on 2025-12-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedOutCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('summer', 'Summer'), ('repeat', 'Repeat'), ('carry', 'Carry')], max_length=10)),
                ('final_exam_full_score', models.FloatField(blank=True, null=True)),
                ('student_final_score', models.FloatField(blank=True, null=True)),
                ('dropped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student_records.droppedout')),
            ],
        ),
    ]
