# Generated by Django 5.2.7 on 2025-12-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0002_droppedoutcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='droppedoutcourse',
            old_name='student_final_score',
            new_name='final_exam_score',
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='is_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='midterm_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='section_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppedoutcourse',
            name='year_work_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='droppedoutcourse',
            name='course_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('summer', 'Summer'), ('repeat', 'Repeat'), ('carry', 'Carry')], max_length=10),
        ),
    ]
