# Generated by Django 5.2.7 on 2025-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'لم تُقيَّم بعد'), ('passed', 'ناجح'), ('failed', 'راسب')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'مادة مترحلة',
                'verbose_name_plural': 'المواد المترحلة',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('course_type', models.CharField(choices=[('normal', 'عادي'), ('summer', 'صيفي'), ('carry', 'مترحل')], default='normal', max_length=20)),
                ('semester', models.CharField(choices=[('first', 'الفصل الدراسي الأول'), ('second', 'الفصل الدراسي الثاني')], default='first', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSectionAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10, verbose_name='سكشن')),
            ],
        ),
    ]
