# Generated by Django 5.2.7 on 2025-10-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrycourse',
            name='carried_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_courses', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='carrycourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_instances', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'subject_doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='structure.studentstructure'),
        ),
        migrations.AddField(
            model_name='carrycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_carry_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursesectionassistant',
            name='assistant',
            field=models.ForeignKey(limit_choices_to={'role': 'teaching_assistant'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='coursesectionassistant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assistants', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='carrycourse',
            unique_together={('student', 'course', 'carried_year')},
        ),
    ]
