# Generated by Django 5.2.7 on 2025-10-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DATA', 'Data Science'), ('CYBER', 'Cyber Security'), ('AUTOTRONICS', 'Autotronics'), ('MECHATRONICS', 'Mechatronics'), ('GARMENT_MANUFACTURING', 'Garment Manufacturing'), ('CONTROL_SYSTEMS', 'Control Systems')], max_length=25)),
                ('year', models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('summer', 'Summer Course'), ('retake_year', 'Retake Year')], default='active', max_length=20)),
                ('failed_courses_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_courses', models.ManyToManyField(blank=True, related_name='failed_structures', to='courses.course')),
            ],
            options={
                'verbose_name': 'Student Structure',
                'verbose_name_plural': 'Student Structures',
                'unique_together': {('department', 'year', 'status')},
            },
        ),
        migrations.CreateModel(
            name='RepeatCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_courses', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_registrations', to='accounts.student')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_registrations', to='structure.studentstructure')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني')], default='first', max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='accounts.student')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='structure.studentstructure')),
            ],
        ),
        migrations.CreateModel(
            name='CarryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'لم يُعاد بعد'), ('passed', 'تم النجاح'), ('failed', 'سقط مرة أخرى')], default='pending', max_length=15)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_summer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_instances', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_records', to='accounts.student')),
                ('from_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_from', to='structure.studentstructure')),
                ('to_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_to', to='structure.studentstructure')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_courses', to='courses.course')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_registrations', to='structure.studentstructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_registrations', to='accounts.student')),
            ],
        ),
    ]
