# Generated by Django 5.2.7 on 2025-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summercourseregistration',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='summercourseregistration',
            name='grade',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
    ]
