# Generated by Django 5.2.7 on 2025-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_summercourseregistration_is_evaluated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrycourse',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
