# Generated by Django 5.2.7 on 2025-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_carrycourse_is_evaluated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrycourse',
            name='is_summer',
        ),
        migrations.AddField(
            model_name='carrycourse',
            name='final_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repeatcourseregistration',
            name='final_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repeatcourseregistration',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summercourseregistration',
            name='final_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrycourse',
            name='grade',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='repeatcourseregistration',
            name='grade',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
    ]
