# Generated by Django 5.2.7 on 2025-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_remove_carrycourse_is_summer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrycourse',
            name='state',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='repeatcourseregistration',
            name='state',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='summercourseregistration',
            name='state',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('راسب', 'راسب'), ('-', 'لم يحدد بعد')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrycourse',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeatcourseregistration',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summercourseregistration',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
