# Generated by Django 5.2.7 on 2025-11-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_carrycourse_state_repeatcourseregistration_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrycourse',
            old_name='final_exam_score',
            new_name='final_exam_full_score',
        ),
        migrations.RenameField(
            model_name='carrycourse',
            old_name='grade',
            new_name='student_final_score',
        ),
        migrations.RenameField(
            model_name='repeatcourseregistration',
            old_name='final_exam_score',
            new_name='final_exam_full_score',
        ),
        migrations.RenameField(
            model_name='repeatcourseregistration',
            old_name='grade',
            new_name='student_final_score',
        ),
        migrations.RenameField(
            model_name='summercourseregistration',
            old_name='final_exam_score',
            new_name='final_exam_full_score',
        ),
        migrations.RenameField(
            model_name='summercourseregistration',
            old_name='grade',
            new_name='student_final_score',
        ),
        migrations.RemoveField(
            model_name='carrycourse',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repeatcourseregistration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='summercourseregistration',
            name='status',
        ),
    ]
