# Generated by Django 5.2.7 on 2025-11-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_rename_final_exam_score_carrycourse_final_exam_full_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatcourseregistration',
            name='retake_attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
