# Generated by Django 5.2.7 on 2025-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_repeatcourseregistration_retake_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatcourseregistration',
            name='retake_attempt_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
