# Generated by Django 5.2.7 on 2026-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_repeatcourseregistration_retake_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstructure',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('summer', 'Summer Course'), ('retake_year', 'Retake Year'), ('dropped_out', 'Dropped Out'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
